/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/sign_up'
import { Route as IndexImport } from './routes/index'
import { Route as RecipesIdImport } from './routes/recipes.$id'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/sign_up',
  path: '/sign_up',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RecipesIdRoute = RecipesIdImport.update({
  id: '/recipes/$id',
  path: '/recipes/$id',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/sign_up': {
      id: '/sign_up'
      path: '/sign_up'
      fullPath: '/sign_up'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/recipes/$id': {
      id: '/recipes/$id'
      path: '/recipes/$id'
      fullPath: '/recipes/$id'
      preLoaderRoute: typeof RecipesIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign_up': typeof SignupRoute
  '/recipes/$id': typeof RecipesIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign_up': typeof SignupRoute
  '/recipes/$id': typeof RecipesIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/sign_up': typeof SignupRoute
  '/recipes/$id': typeof RecipesIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sign_up' | '/recipes/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sign_up' | '/recipes/$id'
  id: '__root__' | '/' | '/sign_up' | '/recipes/$id'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignupRoute: typeof SignupRoute
  RecipesIdRoute: typeof RecipesIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignupRoute: SignupRoute,
  RecipesIdRoute: RecipesIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/sign_up",
        "/recipes/$id"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/sign_up": {
      "filePath": "sign_up.tsx"
    },
    "/recipes/$id": {
      "filePath": "recipes.$id.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
